import type { Metadata } from "next";
import { Plus_Jakarta_Sans as FontJakarta } from "next/font/google";
import "./globals.css";
import TanstackProvider from "@/components/common/tanstack-provider";

const fontJakarta = FontJakarta({
  subsets: ["cyrillic-ext"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fontJakarta.className}>
        <TanstackProvider>
          {children}
        </TanstackProvider>
      </body>
    </html>
  );
}
