import type { Metadata } from "next";
import { Fira_Mono as FontMono } from "next/font/google";
import "./globals.css";
import TanstackProvider from "@/components/common/tanstack-provider";
export const dynamic = 'force-dynamic'

const fontMono = FontMono({
  subsets: ["latin"],
  weight: "500",
  adjustFontFallback: false
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fontMono.className}>
        <TanstackProvider>
          {children}
        </TanstackProvider>
      </body>
    </html>
  );
}
